name: main

on:
  push:
    paths-ignore: [ "docs/**" ]
    branches: [ main ]
  pull_request:
    paths-ignore: [ "docs/**" ]
    branches: [ main ]
  schedule:
    - cron: '15 19 1 * *'

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
        - os: macos-latest
          COMPILER: clang
          NAME: macos
        - os: ubuntu-latest
          COMPILER: gcc
          NAME: linux
    steps:
    - uses: actions/checkout@v4
    - name: Env setup
      if: ${{ matrix.NAME == 'linux' }}
      run: |
        sudo apt update
        sudo apt install valgrind
    - name: Build
      run: make CC=${{ matrix.COMPILER }}
    - name: Memory check
      if: ${{ matrix.NAME == 'linux' }}
      run: |
        valgrind --leak-check=full --show-leak-kinds=all --errors-for-leak-kinds=all \
          --quiet --error-exitcode=1 ./mandelbrot -m 100
        valgrind --leak-check=full --show-leak-kinds=all --errors-for-leak-kinds=all \
          --quiet --error-exitcode=1 ./mandelbrot -a histogram -m 100
        valgrind --leak-check=full --show-leak-kinds=all --errors-for-leak-kinds=all \
          --quiet --error-exitcode=1 ./mandelbrot -a simple -m 100
