name: main

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
        - os: macos-latest
          COMPILER: clang
        - os: ubuntu-latest
          COMPILER: gcc      
    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: make CC=${{ matrix.COMPILER }}
